spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${user.dir}/data/map-game.db
    hikari:
      maximum-pool-size: 1
  flyway:
    enabled: true
    locations: classpath:db/migration/sqlite
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
